PLUGINS = ["netbox_geoview"]

PLUGINS_CONFIG = {
    "netbox_geoview": {
        "start_latitude": 47.59397,
        "start_longitude": 14.12456,
        "start_zoom": 7,
        "min_zoom": 2,
        "max_zoom": 19,
        "default_tile_layer": "OpenStreetMap",
        "scroll_wheel_zoom": True,
        "site_marker": {
            "color": "#f1c40f",
            "symbol": "",
            "icon_url": "",
            "icon_size": [28, 40],
            "icon_anchor": [14, 40],
            "popup_anchor": [0, -34],
        },
        "site_group_markers": {
            "burgenland": {"color": "#f1c40f"},
            "karnten": {"color": "#e74c3c"},
            "niederosterreich": {"color": "#3498db"},
            "oberosterreich": {"color": "#2ecc71"},
            "salzburg": {"color": "#ff69b4"},
            "steiermark": {"color": "#16a085"},
            "tirol": {"color": "#9b59b6"},
            "vorarlberg": {"color": "#34495e"},
            "wien": {"color": "#f39c12"},
        },
        "tile_layers": [
            {
                "name": "OpenStreetMap",
                "url": "https://tile.openstreetmap.org/{z}/{x}/{y}.png",
                "attribution": "&copy; OpenStreetMap contributors",
            },
            {
                "name": "OpenStreetMap DE",
                "url": "https://tile.openstreetmap.de/{z}/{x}/{y}.png",
                "attribution": "&copy; OpenStreetMap contributors",
            },
            {
                "name": "OpenStreetMap HOT",
                "url": "https://a.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png",
                "attribution": "&copy; OpenStreetMap contributors, Humanitarian OpenStreetMap Team",
            },
            {
                "name": "MapTiler Satellite",
                "url": "https://api.maptiler.com/maps/satellite/{z}/{x}/{y}.jpg",
                "attribution": "&copy; MapTiler",
                "query": {
                    "key": "YOUR_MAPTILER_API_KEY",
                },
            },
            {
                "name": "MapTiler Hybrid",
                "url": "https://api.maptiler.com/maps/hybrid/{z}/{x}/{y}.png",
                "attribution": "&copy; MapTiler",
                "query": {
                    "key": "YOUR_MAPTILER_API_KEY",
                },
            },
        ],
        "tile_provider_url": "https://tile.openstreetmap.org/{z}/{x}/{y}.png",
        "popup_sections": {
            "site": [
                {
                    "title": "Core",
                    "mode": "table",
                    "fields": [
                        "id",
                        "name",
                        "slug",
                        "status",
                        "region",
                        "group",
                        "tenant",
                        "facility",
                        "time_zone",
                        "description",
                        "physical_address",
                        "shipping_address",
                        "latitude",
                        "longitude",
                        "comments",
                        "created",
                        "last_updated",
                    ],
                },
                {
                    "title": "Counts",
                    "mode": "table",
                    "fields": [
                        "circuit_count",
                        "device_count",
                        "prefix_count",
                        "rack_count",
                        "virtualmachine_count",
                        "vlan_count",
                    ],
                },
                {"title": "ASNs", "mode": "list", "field": "asns"},
                {"title": "Tags", "mode": "list", "field": "tags"},
                {"title": "Custom Fields", "mode": "table", "field": "custom_fields"},
            ],
            "device": [
                {
                    "title": "Core",
                    "mode": "table",
                    "fields": [
                        "id",
                        "name",
                        "status",
                        "site",
                        "role",
                        "device_type",
                        "platform",
                        "tenant",
                        "serial",
                        "asset_tag",
                        "latitude",
                        "longitude",
                        "created",
                        "last_updated",
                    ],
                },
                {"title": "Tags", "mode": "list", "field": "tags"},
                {"title": "Custom Fields", "mode": "table", "field": "custom_fields"},
            ],
        },
    }
}
